package com.mrpeel.cricketbattingtracker.services

/**
 * Auto-generated by generate_kotlin_forest.py
 * Contains optimized bottom-hand reclassification and shockwave thresholds.
 */
object ShotEnhancementConfig {
    const val POLAR_SHOCKWAVE_THRESHOLD = 24.5f
    const val WATCH_SHOCKWAVE_THRESHOLD = 4.0000f
}
