package com.mrpeel.cricketbattingtracker.services

/**
 * Auto-generated by optimize_shot_enhancement.py
 * Contains optimized bottom-hand reclassification and shockwave thresholds.
 */
object ShotEnhancementConfig {
    const val DRIVE_TO_POWER_GYRO_RATIO = 1.0000f
    const val DRIVE_TO_POWER_ACC_PEAK = 32.0000f

    const val FLICK_TO_GUIDE_GYRO_RATIO = 0.3000f
    const val FLICK_TO_GUIDE_GYRO_PEAK = 0.0500f

    const val PULL_TO_SLOG_GYRO_RATIO = 1.1000f
    const val PULL_TO_SLOG_GYRO_PEAK = 0.1500f

    const val POLAR_SHOCKWAVE_THRESHOLD = 24.5f
    const val WATCH_SHOCKWAVE_THRESHOLD = 18.0f
}
